import { type RouteConfig, index, layout, route } from "@react-router/dev/routes";

export default [
  index("routes/login.tsx"),

  layout("pages/layouts/navbar.tsx", [
    route("home", "routes/home.tsx"),
    route("budgetAdvisorChatbot", "routes/budgetAdvisorChatbot.tsx"),
    route("budgets", "routes/budgetList.tsx"),
    route("budgets/create", "routes/budgetCreate.tsx"),
    route("budgets/edit/:id", "routes/budgetEdit.tsx"),
    route("available-items", "routes/availableItems.tsx"),
    route("products", "routes/productList.tsx"),
    route("products/create", "routes/productCreate.tsx"),
    route("products/edit/:id", "routes/productEdit.tsx"),
    route("products/info/:id", "routes/productInfo.tsx"),
    route("warehouses", "routes/warehouseList.tsx"),
    route("warehouses/create", "routes/warehouseCreate.tsx"),
    route("warehouses/edit/:id", "routes/warehouseEdit.tsx"),
    route("warehouses/info/:id", "routes/warehouseInfo.tsx"),
    route("users", "routes/userList.tsx"),
    route("users/create", "routes/userCreate.tsx"),
    route("users/edit/:id", "routes/userEdit.tsx"),
    route("users/info/:id", "routes/userInfo.tsx"),
    route("transfer-suggestions", "routes/transferSuggestions.tsx"),
    route("donation-suggestions", "routes/donationSuggestions.tsx"),
    route("orders", "routes/orderList.tsx"),
    route("orders/place", "routes/orderPlace.tsx"),
    route("orders/info/:id", "routes/orderInfo.tsx"),
    route("my-orders", "routes/myOrders.tsx"),
    route("warehouse-transfers", "routes/warehouseTransferList.tsx"),
    route("warehouse-transfers/create", "routes/warehouseTransferCreate.tsx"),
    route("warehouse-transfers/info/:id", "routes/warehouseTransferInfo.tsx"),
    route("warehouse-transfers/edit/:id", "routes/warehouseTransferEdit.tsx"),
    route("trips", "routes/tripList.tsx"),
    route("trips/create", "routes/tripCreate.tsx"),
    route("trips/info/:id", "routes/tripInfo.tsx"),
    route("trips/edit/:id", "routes/tripEdit.tsx"),
    route("supplier-products", "routes/supplierProducts.tsx"),
    route("supplier-product-records", "routes/supplierProductRecords.tsx"),
    route("register-product-record", "routes/registerProductRecord.tsx"),
    route("myTruck", "routes/myTruck.tsx"),
    route("myTrips", "routes/myTrips.tsx"),
    route("myTransfers", "routes/myTransfers.tsx"),
    route("business-insights", "routes/businessInsights.tsx"),
    route("analytics", "routes/analytics.tsx"),
  ]),
] satisfies RouteConfig;
